### ISSUE TITLE
SRAM support for ASCII mapper

### ISSUE THREAD

**Issue by atssada** [RBSC/MultiMapperCartridge#2]
Really appreciated to this project.

One request is, can I identify address of LZ93A13 mapper when A8 is enabled? so that I can modify the card to support SDRAM..

https://msxprojects.blogspot.com/2020/12/diy-assembling-1-mb-ascii-megaflashrom.html

Best,
Kim.

**Comment by Wierzbowsky** [comment]
The project is not open-source, so we won't share the firmware in order to allow further modifications, sorry.
